import { ArrowUpRight, BookOpen, CheckCircle2, Clock3, Database, ExternalLink, FileCheck2, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Button, Card, DemoBadge, Modal } from "../components/ui";
import { resourceCards, trustedSources, type KnowledgeSource } from "../mock/data";

export default function ResourcesPage() {
  const [tab, setTab] = useState<"library" | "sources">("library");
  const [resource, setResource] = useState<(typeof resourceCards)[number] | null>(null);
  const [source, setSource] = useState<KnowledgeSource | null>(null);
  return <div className="page">
    <div className="page-heading"><div><span className="eyebrow">Información local y trazable</span><h1>Biblioteca de recursos</h1><p>Contenido general de demostración y un catálogo de fuentes para que el producto no improvise afirmaciones sensibles.</p></div><DemoBadge>Actualizado 7 sep 2026</DemoBadge></div>
    <div className="resource-tabs" role="tablist"><button role="tab" aria-selected={tab === "library"} className={tab === "library" ? "active" : ""} onClick={() => setTab("library")}><BookOpen size={18} /> Recursos breves</button><button role="tab" aria-selected={tab === "sources"} className={tab === "sources" ? "active" : ""} onClick={() => setTab("sources")}><Database size={18} /> Base de fuentes</button></div>
    {tab === "library" ? <><div className="scope-note resource-scope"><ShieldCheck size={20} /><div><strong>Contenido educativo, no clínico</strong><p>No incluye diagnósticos, puntuaciones ni recomendaciones personalizadas. Puedes detener cualquier práctica si no te resulta cómoda.</p></div></div><div className="resource-grid">{resourceCards.map((item) => <Card className="resource-card" key={item.id}><span className="resource-tag">{item.tag}</span><h2>{item.title}</h2><p>{item.description}</p><span className="resource-time"><Clock3 size={16} /> {item.time}</span><Button variant="secondary" onClick={() => setResource(item)}>Abrir recurso</Button></Card>)}</div></> : <><div className="knowledge-intro"><div className="knowledge-icon"><Database /></div><div><h2>Catálogo local de evidencia y reglas de producto</h2><p>Esta no es una base de pacientes. Es un archivo versionado dentro del frontend con fuentes, fecha de verificación y la decisión de diseño que sustenta cada una.</p></div></div><div className="source-list">{trustedSources.map((item) => <button className="source-row" key={item.id} onClick={() => setSource(item)}><span className={`source-category ${item.category}`}>{item.category}</span><span><strong>{item.title}</strong><small>{item.organization}</small></span><span className="verified"><CheckCircle2 size={16} /> Verificada {item.verifiedAt}</span><ArrowUpRight size={18} /></button>)}</div><Card className="excluded-card"><FileCheck2 size={23} /><div><h3>Cuestionarios de tamizaje: autorreporte, no diagnóstico</h3><p>PHQ-9, GAD-7, ASRS v1.1 y PCL-5 están disponibles en la sección Tamizaje como autorreporte informativo local: KAHY solo muestra la banda de interpretación publicada por cada instrumento, nunca un nivel de riesgo calculado. Una versión clínica operativa seguiría necesitando protocolo de seguimiento y supervisión profesional.</p></div></Card></>}
    {resource && <Modal title={resource.title} onClose={() => setResource(null)}><div className="reading-modal"><span className="resource-tag">{resource.tag} · {resource.time}</span><p>{resource.body}</p><div className="scope-note"><ShieldCheck size={18} /><p>Información general. No sustituye una recomendación profesional adaptada a tu situación.</p></div><Button className="full-width" onClick={() => setResource(null)}>Terminar</Button></div></Modal>}
    {source && <Modal title={source.title} onClose={() => setSource(null)}><div className="source-modal"><DemoBadge>{source.organization}</DemoBadge><h3>Qué aporta</h3><p>{source.summary}</p><h3>Cómo influye en KAHY</h3><p>{source.productRule}</p><p className="verified-line"><CheckCircle2 size={17} /> Última verificación local: {source.verifiedAt}</p><a className="button button--secondary full-width" href={source.url} target="_blank" rel="noreferrer">Abrir fuente oficial <ExternalLink size={17} /></a></div></Modal>}
  </div>;
}
